// GENERATED by data/cafe/emit.py — do not edit.
// Zones only. The map module in data/ carries the tile arrays; the backend
// needs just the fixtures, so they are split to keep the function bundle small.

export const PLACE_NAME = "the Stanford campus cafe";
export const LABEL = "Today \u2014 one staffed register";
export const TILE_FEET = 3;
export const ZONES = [
  {
    "id": "display_case",
    "role": "display_case",
    "rect": [
      7,
      5,
      12,
      5
    ],
    "approach": [
      [
        6,
        5
      ],
      [
        7,
        4
      ],
      [
        7,
        6
      ],
      [
        8,
        4
      ],
      [
        8,
        6
      ],
      [
        9,
        4
      ],
      [
        9,
        6
      ],
      [
        10,
        4
      ],
      [
        10,
        6
      ],
      [
        11,
        4
      ],
      [
        11,
        6
      ],
      [
        12,
        4
      ],
      [
        12,
        6
      ],
      [
        13,
        5
      ]
    ],
    "service": {
      "seconds": 25,
      "staffed": false,
      "automates": true
    },
    "queue": [],
    "note": "Grab-and-go. The tray model handles these in one shot."
  },
  {
    "id": "espresso_bar",
    "role": "espresso_bar",
    "rect": [
      3,
      5,
      4,
      5
    ],
    "approach": [
      [
        2,
        5
      ],
      [
        3,
        4
      ],
      [
        4,
        4
      ],
      [
        5,
        5
      ]
    ],
    "service": {
      "seconds": 95,
      "staffed": true,
      "automates": false
    },
    "queue": [],
    "note": "Made-to-order. The bottleneck a kiosk cannot remove."
  },
  {
    "id": "drinks",
    "role": "drinks",
    "rect": [
      17,
      5,
      18,
      5
    ],
    "approach": [
      [
        16,
        5
      ],
      [
        17,
        4
      ],
      [
        17,
        6
      ],
      [
        18,
        4
      ],
      [
        18,
        6
      ],
      [
        19,
        5
      ]
    ],
    "service": {
      "seconds": 20,
      "staffed": false,
      "automates": true
    },
    "queue": [],
    "note": null
  },
  {
    "id": "espresso_pickup",
    "role": "espresso_pickup",
    "rect": [
      15,
      5,
      15,
      5
    ],
    "approach": [
      [
        14,
        5
      ],
      [
        15,
        4
      ],
      [
        16,
        5
      ]
    ],
    "service": {
      "seconds": 0,
      "staffed": false,
      "automates": false
    },
    "queue": [],
    "note": "Handoff shelf. Zero service time, but this is where the SECOND queue forms."
  },
  {
    "id": "register",
    "role": "register",
    "rect": [
      14,
      6,
      15,
      6
    ],
    "approach": [
      [
        13,
        6
      ],
      [
        14,
        5
      ],
      [
        14,
        7
      ],
      [
        15,
        7
      ],
      [
        16,
        6
      ]
    ],
    "service": {
      "seconds": 38,
      "staffed": true,
      "automates": false
    },
    "queue": [],
    "note": "The incumbent lane Mashgin is displacing. Order + pay in one stop."
  }
] as const;
export const STAFF: Record<string, number> = {
  "cashiers": 1,
  "baristas": 1
};
