// GENERATED FILE — DO NOT EDIT.
// Source: prompts/genagents/**/*.txt  (vendored verbatim from joonspk-research/genagents, MIT)
// Regenerate: node scripts/gen-templates.mjs
//
// These strings are the research contribution. Editing them here — or "cleaning
// them up" — is the single easiest way to silently deviate from the published
// architecture. Change the .txt files, add a versioned variant, and regenerate.

export const TEMPLATES: Record<string, string> = {
  "interaction/categorical_resp/batch_v1": "Variables: \n\nNote: basically main version (ver 3) but with \"reasoning\" step\n\n<commentblockmarker>###</commentblockmarker>\n!<INPUT 0>!\n\n=====\n\nTask: What you see above is an interview transcript. Based on the interview transcript, I want you to predict the participant's survey responses. All questions are multiple choice where you must guess from one of the options presented. \n\nAs you answer, I want you to take the following steps: \nStep 1) Describe in a few sentences the kind of person that would choose each of the response options. (\"Option Interpretation\")\nStep 2) For each response options, reason about why the Participant might answer with the particular option. (\"Option Choice\")\nStep 3) Write a few sentences reasoning on which of the option best predicts the participant's response (\"Reasoning\")\nStep 4) Predict how the participant will actually respond in the survey. Predict based on the interview and your thoughts, but ultimately, DON'T over think it. Use your system 1 (fast, intuitive) thinking. (\"Response\")\n\nHere are the questions: \n\n!<INPUT 1>!\n\n-----\n\nOutput format -- output your response in json, where you provide the following: \n\n{\"1\": {\"Q\": \"<repeat the question you are answering>\",\n       \"Option Interpretation\": {\n            \"<option 1>\": \"a few sentences the kind of person that would choose each of the response options\",\n            \"<option 2>\": \"...\"},\n       \"Option Choice\": {\n            \"<option 1>\": \"reasoning about why the participant might choose each of the options\",\n            \"<option 2>\": \"...\"},\n       \"Reasoning\": \"<reasoning on which of the option best predicts the participant's response>\",\n       \"Response\": \"<your prediction on how the participant will answer the question>\"},\n \"2\": {\"Q\": \"<repeat the question you are answering>\",\n       \"Option Interpretation\": {\n            \"<option 1>\": \"a few sentences the kind of person that would choose each of the response options\",\n            \"<option 2>\": \"...\"},\n       \"Option Choice\": {\n            \"<option 1>\": \"reasoning about why the participant might choose each of the options\",\n            \"<option 2>\": \"...\"},\n       \"Reasoning\": \"<reasoning on which of the option best predicts the participant's response>\",\n       \"Response\": \"<your prediction on how the participant will answer the question>\"},\n  ...}",
  "interaction/categorical_resp/singular_v1": "Variables: \n\nNote: basically main version (ver 3) but with \"reasoning\" step\n\n<commentblockmarker>###</commentblockmarker>\n!<INPUT 0>!\n\n=====\n\nTask: What you see above is an interview transcript. Based on the interview transcript, I want you to predict the participant's survey responses. The question is a multiple choice where you must guess from one of the options presented. \n\nAs you answer, I want you to take the following steps: \nStep 1) Describe in a few sentences the kind of person that would choose each of the response options. (\"Option Interpretation\")\nStep 2) For each response options, reason about why the Participant might answer with the particular option. (\"Option Choice\")\nStep 3) Write a few sentences reasoning on which of the option best predicts the participant's response (\"Reasoning\")\nStep 4) Predict how the participant will actually respond in the survey. Predict based on the interview and your thoughts, but ultimately, DON'T over think it. Use your system 1 (fast, intuitive) thinking. (\"Response\")\n\nHere is the question: \n\n!<INPUT 1>!\n\n-----\n\nOutput format -- output your response in json, where you provide the following: \n\n{\"1\": {\"Q\": \"<repeat the question you are answering>\",\n       \"Option Interpretation\": {\n            \"<option 1>\": \"a few sentences the kind of person that would choose each of the response options\",\n            \"<option 2>\": \"...\"},\n       \"Option Choice\": {\n            \"<option 1>\": \"reasoning about why the participant might choose each of the options\",\n            \"<option 2>\": \"...\"},\n       \"Reasoning\": \"<reasoning on which of the option best predicts the participant's response>\",\n       \"Response\": \"<your prediction on how the participant will answer the question>\"}}",
  "interaction/numerical_resp/batch_v1": "Variables: \n\nNote: basically main version (ver 3) but with \"reasoning\" step\n\n<commentblockmarker>###</commentblockmarker>\n!<INPUT 0>!\n\n=====\n\nTask: What you see above is an interview transcript. Based on the interview transcript, I want you to predict the participant's survey responses. For all questions, you should output a number that is in the range that was specified for that question. \n\nAs you answer, I want you to take the following steps: \nStep 1) Describe in a few sentences the kind of person that would choose each end of the range. (\"Range Interpretation\")\nStep 2) Write a few sentences reasoning on which of the option best predicts the participant's response (\"Reasoning\")\nStep 3) Predict how the participant will actually respond. Predict based on the interview and your thoughts, but ultimately, DON'T over think it. Use your system 1 (fast, intuitive) thinking. (\"Response\")\n\nHere are the questions: \n\n!<INPUT 1>!\n\n-----\n\nOutput format -- output your response in json, where you provide the following: \n\n{\"1\": {\"Q\": \"<repeat the question you are answering>\",\n       \"Range Interpretation\": {\n            \"<option 1>\": \"a few sentences about the kind of person that would choose each end of the range\",\n            \"<option 2>\": \"...\"},\n       \"Reasoning\": \"<reasoning on which of the option best predicts the participant's response>\",\n       \"Response\": <a single !<INPUT 2>! value that best represents your prediction on how the participant's answer>},\n \"2\": {\"Q\": \"<repeat the question you are answering>\",\n       \"Range Interpretation\": {\n            \"<option 1>\": \"a few sentences about the kind of person that would choose each end of the range\",\n            \"<option 2>\": \"...\"},\n       \"Reasoning\": \"<reasoning on which of the option best predicts the participant's response>\",\n       \"Response\": <your prediction on how the participant will answer the question>},\n  ...}",
  "interaction/numerical_resp/singular_v1": "Variables: \n\nNote: basically main version (ver 3) but with \"reasoning\" step\n\n<commentblockmarker>###</commentblockmarker>\n!<INPUT 0>!\n\n=====\n\nTask: What you see above is an interview transcript. Based on the interview transcript, I want you to predict the participant's survey response to a question. You should output a number that is in the range that was specified for that question. \n\nAs you answer, I want you to take the following steps: \nStep 1) Describe in a few sentences the kind of person that would choose each end of the range. (\"Range Interpretation\")\nStep 2) Write a few sentences reasoning on which of the option best predicts the participant's response (\"Reasoning\")\nStep 3) Predict how the participant will actually respond. Predict based on the interview and your thoughts, but ultimately, DON'T over think it. Use your system 1 (fast, intuitive) thinking. (\"Response\")\n\nHere is the question: \n\n!<INPUT 1>!\n\n-----\n\nOutput format -- output your response in json, where you provide the following: \n\n{\"1\": {\"Q\": \"<repeat the question you are answering>\",\n       \"Range Interpretation\": {\n            \"<option 1>\": \"a few sentences about the kind of person that would choose each end of the range\",\n            \"<option 2>\": \"...\"},\n       \"Reasoning\": \"<reasoning on which of the option best predicts the participant's response>\",\n       \"Response\": <a single !<INPUT 2>! value that best represents your prediction on how the participant's answer>}}",
  "interaction/utternace/utterance_v1": "<commentblockmarker>###</commentblockmarker>\n<Background information about the Character>\n!<INPUT 0>!\n\n<End of background information about the Character>\n=====\n<Dialogue so far>\n!<INPUT 1>!\n\n!<INPUT 2>!\n\n<End of dialogue so far>\n\nTask: First, study the background information that I provided you about a fictional subject above. We are writing a dialogue between the subject above, and me. Given the dialogue so far, generate the next utterance that the character will speak. \n\nOutput format -- output your response in json, where you provide the following: \n{\"utterance\": \"[...]\"} ",
  "memory_stream/importance_score/batch_v1": "Variables: \n!<INPUT 0>!: Observations\n\n<commentblockmarker>###</commentblockmarker>\n!<INPUT 0>!\n---\nTask: Above is a list of observations about a fictional human subject. For each item, rate its importance on a scale from 0 to 100, where 0 represents 'not important' and 100 represents 'very important' for understanding the subject.\nOutput format: Json dictionaries of the following format: \n{\n\"Item  1\": <int importance score (range: 0 to 100) for item 1>,\n\"Item  2\": <int importance score (range: 0 to 100) for item 2>, ...\n}",
  "memory_stream/importance_score/singular_v1": "Variables: \n!<INPUT 0>!: Observations\n\n<commentblockmarker>###</commentblockmarker>\n!<INPUT 0>!\n---\nTask: Above is an observation (\"Item 1\") about a fictional human subject. Rate its importance on a scale from 0 to 100, where 0 represents 'not important' and 100 represents 'very important' for understanding the subject.\nOutput format: Json dictionaries of the following format: \n{\n\"Item  1\": <int importance score (range: 0 to 100) for item 1>\n}",
  "memory_stream/reflection/batch_v1": "Variables: \n!<INPUT 0>!: observations\n!<INPUT 1>!: reflection count\n!<INPUT 2>!: anchor\n<commentblockmarker>###</commentblockmarker>\n!<INPUT 0>!\n---\nTask: Above are observations about a fictional human subject. Write a list of !<INPUT 1>! reflections (in first person voice, from the perspective of the subject) that you can infer from the observations above about the subject on the following anchoring topic/phrase: \"!<INPUT 2>!\". \n\nOutput format: Json dictionaries of the following format: \n{\n  \"reflection\": [\n     \"<fill in>\",\n     \"<fill in>\", ... \n  ]\n}",
  "memory_stream/reflection/singular_v1": "Variables: \n!<INPUT 0>!: observations\n!<INPUT 1>!: reflection count\n!<INPUT 2>!: anchor\n<commentblockmarker>###</commentblockmarker>\n!<INPUT 0>!\n---\nTask: Above are observations about a fictional human subject. Write one reflection (in first person voice, from the perspective of the subject) that you can infer from the observations above about the subject on the following anchoring topic/phrase: \"!<INPUT 2>!\". \n\nOutput format: Json dictionaries of the following format: \n{\n  \"reflection\": [\n     \"<fill in>\"\n  ]\n}",
};

/**
 * Port of `simulation_engine/gpt_structure.py:29 generate_prompt`.
 *
 * Upstream, exactly:
 *   prompt_input = [str(i) for i in prompt_input]
 *   prompt = read(file)
 *   for count, input_text in enumerate(prompt_input):
 *       prompt = prompt.replace(f"!<INPUT {count}>!", input_text)
 *   if "<commentblockmarker>###</commentblockmarker>" in prompt:
 *       prompt = prompt.split("<commentblockmarker>###</commentblockmarker>")[1]
 *   return prompt.strip()
 *
 * Order matters and is preserved: substitution runs over the WHOLE file
 * (header included) and the header is discarded afterwards. Stripping first
 * gives the same bytes in every current template, but diverges the moment a
 * template's header changes or a substituted value contains the marker.
 *
 * `split(marker)[1]` takes the segment BETWEEN the first and second marker —
 * not everything after the first. Same thing for a single-marker file; not the
 * same if a template ever gains a second marker.
 */
export function renderTemplate(key: string, inputs: (string | number)[]): string {
  const raw = TEMPLATES[key];
  if (raw === undefined) {
    throw new Error(`Unknown prompt template: ${key}. Known: ${Object.keys(TEMPLATES).join(', ')}`);
  }

  let prompt = raw;
  inputs.forEach((value, i) => {
    prompt = prompt.replaceAll(`!<INPUT ${i}>!`, String(value));
  });

  const marker = '<commentblockmarker>###</commentblockmarker>';
  if (prompt.includes(marker)) {
    prompt = prompt.split(marker)[1];
  }

  return prompt.trim();
}
