#!/usr/bin/env python3
"""Emit Siliconville as a map module the existing renderer already understands.

    python3 data/siliconville/emit.py

Writes data/siliconville.js in the same shape as data/gentle.js, so the fork
renders through PixiStaticMap unchanged rather than growing a second renderer.

Buildings, trees and water go in objmap, which in this engine both DRAWS and
BLOCKS. That is the opposite of the stadium, where collision had to be an
invisible tile because the artwork was underneath; here the object IS the
obstacle, so one layer does both jobs.

Also checks that the streets form a single connected network. A campus with no
road frontage looks completely fine in a screenshot and is unreachable the
moment anything has to walk to it.
"""

import json
from collections import deque
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[1]


def main():
    d = json.loads((HERE / "authored.json").read_text())
    W, H = d["width"], d["height"]
    ground, detail, objects = (d["layers"][k] for k in ("ground", "detail", "objects"))
    solid = d["solid"]
    T = {n: i for i, n in enumerate(d["names"])}

    # --- connectivity --------------------------------------------------------
    walk = lambda x, y: 0 <= x < W and 0 <= y < H and not solid[x][y]
    seed = next(((x, y) for x in range(W) for y in range(H)
                 if ground[x][y] == T["asphalt"] and walk(x, y)), None)
    seen = set()
    if seed:
        q = deque([seed])
        while q:
            x, y = q.popleft()
            if (x, y) in seen or not walk(x, y):
                continue
            seen.add((x, y))
            q.extend(((x + 1, y), (x - 1, y), (x, y + 1), (x, y - 1)))

    stranded = []
    for lm in d["landmarks"]:
        # A campus is served if any tile next to its footprint is on the network.
        ok = False
        for x in range(lm["x"] - 1, lm["x"] + lm["w"] + 1):
            for y in range(lm["y"] - 1, lm["y"] + lm["h"] + 1):
                if (x, y) in seen:
                    ok = True
                    break
            if ok:
                break
        if not ok:
            stranded.append(lm["name"])

    free = sum(1 for x in range(W) for y in range(H) if not solid[x][y])
    islands = free - len(seen)

    tw, th = d["atlasCols"] * d["tile"], d["atlasRows"] * d["tile"]
    src = f'''// GENERATED by data/siliconville/author.py + emit.py — do not edit.
// Siliconville: a fork of the front page's world with the park replaced by an
// office park. Same 32px grid, same renderer, same tile format as gentle.js.
//
// The atlas is a procedural BLOCKOUT, not final art — structure first, so the
// layout can be judged before art is bought. Swapping in a real city tileset
// is a tile-index remap against the `tileNames` export below.
//
// Company names are the show's fictional ones on purpose. Pixel recreations of
// live trademarks on a public page carry real risk and buy nothing.

export const label = "Siliconville";
export const tilesetpath = "/assets/siliconville.png";
export const tiledim = {d["tile"]};
export const screenxtiles = {W};
export const screenytiles = {H};
export const tilesetpxw = {tw};
export const tilesetpxh = {th};

export const bgtiles = {json.dumps([ground, detail])};
export const objmap = {json.dumps([objects])};
export const animatedsprites = [];

export const mapwidth = bgtiles[0].length;
export const mapheight = bgtiles[0][0].length;

// Named campuses, for the label overlay. x/y/w/h are in TILES.
export const landmarks = {json.dumps(d["landmarks"])};
export const tileNames = {json.dumps(d["names"])};
'''
    (REPO / "data" / "siliconville.js").write_text(src)

    print(f"wrote data/siliconville.js  {W}x{H} tiles ({W*d['tile']}x{H*d['tile']} px)")
    print(f"  street network reaches {len(seen)} of {free} open tiles")
    if islands:
        print(f"  ! {islands} open tiles are cut off from the streets")
    print(f"  {len(d['landmarks'])} named campuses" +
          (f"  ! stranded: {stranded}" if stranded else ", all with road frontage"))


if __name__ == "__main__":
    main()
