#!/usr/bin/env python3
"""Emit the same city as a 3D plan.

    python3 data/siliconville/emit3d.py

Same layout, different renderer. The 2D emit turns the authored grid into tile
indices; this turns it into geometry: ground surfaces, building masses with
floor counts, trees, water.

The point of keeping ONE generator behind both is that the city plan -- where
the streets run, which block each campus got, what has road frontage -- is the
part that took work and the part worth being correct. Whether it draws as tiles
or as boxes is a rendering decision downstream of it.

Ground ships run-length encoded. Raw it is 12,288 integers of mostly identical
neighbours, and the browser has no use for them one at a time.
"""

import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[1]

# Ground materials the renderer knows how to colour and shade.
SURF = {"grass": 0, "asphalt": 1, "sidewalk": 2, "lot": 3, "water": 4, "plaza": 5}

# Roof palette, carried over from the 2D atlas so both views agree.
ROOF_HEX = {
    "roof_pale": "#c6c6c0", "roof_slate": "#78808e", "roof_sand": "#c4b08e",
    "roof_white": "#dedeDA", "roof_teal": "#6c9a96", "roof_red": "#b06c60",
    "roof_brick": "#8d5a49", "roof_rust": "#7c523e",
}


def _rooms(m, name):
    area = m["w"] * m["h"]
    rooms = [{"id": "lobby", "floor": 0, "kind": "lobby",
              "capacity": max(4, area // 12)}]
    if not name:
        return rooms
    for f in range(1, min(m["floors"], 4)):
        rooms.append({"id": f"meet-{f}", "floor": f, "kind": "meeting",
                      "capacity": max(2, area // 30)})
    rooms.append({"id": "boardroom", "floor": min(m["floors"], 4) - 1,
                  "kind": "investor", "capacity": 6})
    return rooms


def main():
    d = json.loads((HERE / "authored.json").read_text())
    W, H = d["width"], d["height"]
    ground, objects = d["layers"]["ground"], d["layers"]["objects"]
    T = {n: i for i, n in enumerate(d["names"])}

    # --- ground surfaces -----------------------------------------------------
    to_surf = {
        T["grass"]: SURF["grass"], T["grass_dry"]: SURF["grass"],
        T["asphalt"]: SURF["asphalt"], T["lane_h"]: SURF["asphalt"],
        T["lane_v"]: SURF["asphalt"], T["crosswalk_h"]: SURF["asphalt"],
        T["crosswalk_v"]: SURF["asphalt"], T["sidewalk"]: SURF["sidewalk"],
        T["lot"]: SURF["lot"], T["lot_stripe"]: SURF["lot"],
        T["plaza"]: SURF["plaza"],
    }
    flat = []
    for y in range(H):                      # row-major: the renderer reads rows
        for x in range(W):
            flat.append(to_surf.get(ground[x][y], SURF["grass"]))

    # Water overrides whatever ground was under it. Without this the water
    # mesh floats a hair above a green tile and the bay reads as a pond on a
    # lawn -- the ground box top sits higher than the water box top.
    for y in range(H):
        for x in range(W):
            if objects[x][y] == T["water"]:
                flat[y * W + x] = SURF["water"]

    rle, cur, n = [], flat[0], 0
    for v in flat:
        if v == cur:
            n += 1
        else:
            rle += [cur, n]
            cur, n = v, 1
    rle += [cur, n]

    # --- scatter -------------------------------------------------------------
    trees = [[x, y] for x in range(W) for y in range(H) if objects[x][y] == T["tree"]]
    water = [[x, y] for x in range(W) for y in range(H) if objects[x][y] == T["water"]]

    # --- masses --------------------------------------------------------------
    # Landmarks are matched to the mass they sit on so a label can float over
    # the right roof at the right HEIGHT, which is the whole trick in 3D.
    masses = []
    for m in d["masses"]:
        lm = next((l["name"] for l in d["landmarks"]
                   if l["x"] == m["x"] and l["y"] == m["y"]), None)
        masses.append({
            "x": m["x"], "y": m["y"], "w": m["w"], "h": m["h"],
            "floors": m["floors"], "color": ROOF_HEX.get(m["roof"], "#c6c6c0"),
            "style": m.get("style", "slab"), "name": lm,
            "door": m.get("door"), "arches": m.get("arches", []),
            # Rooms an agent can be IN. Floor 0 is always a lobby; named
            # campuses get meeting rooms above it. Capacity is what makes a
            # meetup schedulable — a room that can hold everyone is not a
            # constraint, and constraints are the only thing worth simulating.
            "rooms": _rooms(m, lm),
        })

    src = f'''// GENERATED by data/siliconville/author.py + emit3d.py — do not edit.
// Siliconville as geometry rather than tiles: ground surfaces, building masses
// with floor counts, trees, water.
//
// Same generator as the 2D map (data/siliconville.js). The city PLAN — where
// streets run, which block each campus got, what has road frontage — is the
// part that took work; tiles vs boxes is a rendering choice downstream of it.

export const width = {W};
export const height = {H};
export const surfaces = {{ grass: 0, asphalt: 1, sidewalk: 2, lot: 3, water: 4, plaza: 5 }};

// Row-major [value, runLength, value, runLength, ...] over width*height cells.
export const groundRLE = {json.dumps(rle)};

// x/y/w/h in tiles; floors is storeys, not metres.
export const masses = {json.dumps(masses)};
export const trees = {json.dumps(trees)};

// Street grid, in tiles: [position, width] per artery.
export const vstreets = {json.dumps(d["vstreets"])};
export const hstreets = {json.dumps(d["hstreets"])};
// Where the rooftop letters go, and the exact roof height to rest them on.
export const sign = {json.dumps(d["sign"])};
export const signRoofY = {d["sign"]["floors"]} * 1.6;

// True glyph contours in TILE coordinates, one entry per word. The buildings
// under the words are rasterised to the tile grid and can only make
// staircases; the red form on top is extruded from these outlines so the part
// you actually read is smooth.
export const letterOutlines = {json.dumps(d["sign"].get("outlines", []))};

// Named quarters, in tiles. One source for the map, the balloons and the
// sidebar — three copies of these bounds is how a tenant ends up filed under
// the wrong district in one place and the right one in another.
export const districts = {json.dumps(d["districts"])};

export const bayX = {d["bayX"]};
export const bridgeY = {d["bridgeY"]};
export const freewayY = {d["freewayY"]};
export const water = {json.dumps(water)};
'''
    (REPO / "data" / "siliconville3d.js").write_text(src)

    named = sum(1 for m in masses if m["name"])
    print(f"wrote data/siliconville3d.js  {W}x{H}")
    print(f"  {len(masses)} building masses ({named} named), "
          f"{len(trees)} trees, {len(water)} water tiles")
    print(f"  ground {len(rle)//2} runs for {W*H} cells")


if __name__ == "__main__":
    main()
